services:
  game:
    image: ghcr.io/hong-zhijun/xiuxian:latest
    ports:
      - "30005:80"
    volumes:
      - gamedata:/app/apps/server/.wrangler/state
    env_file:
      - .env
    restart: unless-stopped

volumes:
  gamedata:
